# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30e967ef324bff7a4da86f33c4c591fc0377c07027d24364f4d539e5bd14f959b06ba5f3cad8e34e5b811b3e47c0f4017ba578b8e1aca091a446b88ab40a1c23

test:
  secret_key_base: 9fa16f5020e9fbf6a61465b1b8730dc89af5607fbcb7b0a962166f50169ce6a1c80bd7ccc7ab7131f408f674e83dd8fbb4540fb4d9bfa3006e39d6d070696230

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
